name: PSParallelPipeline Workflow
on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

  release:
    types:
    - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  BUILD_CONFIGURATION: ${{ fromJSON('["Debug", "Release"]')[startsWith(github.ref, 'refs/tags/v')] }}

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build module - Debug
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      if: ${{ env.BUILD_CONFIGURATION == 'Debug' }}

    - name: Build module - Publish
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Build
      if: ${{ env.BUILD_CONFIGURATION == 'Release' }}

    - name: Capture PowerShell Module
      uses: actions/upload-artifact@v3
      with:
        name: PSModule
        path: output/*.nupkg

  test:
    name: test
    needs:
      - build
    runs-on: ${{ matrix.info.os }}
    strategy:
      fail-fast: false
      matrix:
        info:
        - name: PS-5.1
          psversion: '5.1'
          os: windows-latest
        - name: PS-7_Windows
          psversion: '7'
          os: windows-latest
        - name: PS-7_Linux
          psversion: '7'
          os: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore Built PowerShell Module
      uses: actions/download-artifact@v3
      with:
        name: PSModule
        path: output

    - name: Install Built PowerShell Module
      shell: pwsh
      run: |
        $manifestItem = Get-Item ([IO.Path]::Combine('Module', '*.psd1'))
        $moduleName = $manifestItem.BaseName
        $manifest = Test-ModuleManifest -Path $manifestItem.FullName -ErrorAction SilentlyContinue -WarningAction Ignore

        $destPath = [IO.Path]::Combine('output', $moduleName, $manifest.Version)
        if (-not (Test-Path -LiteralPath $destPath)) {
            New-Item -Path $destPath -ItemType Directory | Out-Null
        }

        Get-ChildItem output/*.nupkg | Rename-Item -NewName { $_.Name -replace '.nupkg', '.zip' }

        Expand-Archive -Path output/*.zip -DestinationPath $destPath -Force -ErrorAction Stop

    - name: Run Tests - Windows PowerShell
      if: ${{ matrix.info.psversion == '5.1' }}
      shell: powershell
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Test

    - name: Run Tests - PowerShell
      if: ${{ matrix.info.psversion != '5.1' }}
      shell: pwsh
      run: ./build.ps1 -Configuration $env:BUILD_CONFIGURATION -Task Test

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: Unit Test Results (${{ matrix.info.name }})
        path: ./output/TestResults/Pester.xml

    - name: Upload Coverage Results
      if: always() && !startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Results (${{ matrix.info.name }})
        path: ./output/TestResults/Coverage.xml

    - name: Upload Coverage to codecov
      if: always() && !startsWith(github.ref, 'refs/tags/v')
      uses: codecov/codecov-action@v3
      with:
        files: ./output/TestResults/Coverage.json
        flags: ${{ matrix.info.name }}

  publish:
    name: publish
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
    - build
    - test
    runs-on: windows-latest
    steps:
    - name: Restore Built PowerShell Module
      uses: actions/download-artifact@v3
      with:
        name: PSModule
        path: ./

    - name: Publish to Gallery
      if: github.event_name == 'release'
      shell: pwsh
      run: >-
        dotnet nuget push '*.nupkg'
        --api-key $env:PSGALLERY_TOKEN
        --source 'https://www.powershellgallery.com/api/v2/package'
        --no-symbols
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
