name: Release Publish Workflow
on:
  release:
    types:
    - published

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  POWERSHELL_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  publish:
    name: publish
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.event_name == 'release'
    steps:
    - uses: actions/checkout@v3

    - name: Publish to Gallery
      shell: pwsh
      run: >-
        Publish-Module -Path $PSScriptRoot -NuGetApiKey $env:PSGALLERY_TOKEN
      env:
        PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}